# Site settings
title: Active Grids
email: activegrids@gmail.com
url: https://activegrids.city
description: "Promoting active transportation."

# Contact form: comment the line below if you want to stick with the default PHP contact form
contact: static

# Color settings (hex-codes without the leading hash-tag)
color:
#  primary:  3915AE #purple
#  secondary: 707070 #gray
#  secondary-dark: CB0173 #burgundy
  primary:  CB0173 #burgundy
  secondary: 3915AE #purple
  secondary-dark: 707070 #gray


# Footer settings
footer:
  copyright: Active Grids
  location: Montreal
  social: #Around the Web
  credits: #Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://www.facebook.com/ActiveGrids

# Postal address (add as many lines as necessary)
address:
  - line: Quebec, Canada

# Credits content
credits: 'Activate your grid.'

# Build settings
markdown: kramdown
permalink: pretty
